import * as X from "@xstyled/styled-components";

export type XStyledProps = Partial<
  X.AlignContentProps &
    X.AlignItemsProps &
    X.AlignSelfProps &
    X.AnimationDurationProps &
    X.AnimationProps &
    X.AnimationTimingFunctionProps &
    X.AnimationsProps &
    X.AppearanceProps &
    X.BackgroundAttachmentProps &
    X.BackgroundClipProps &
    X.BackgroundColorProps &
    X.BackgroundImageProps &
    X.BackgroundPositionProps &
    X.BackgroundProps &
    X.BackgroundRepeatProps &
    X.BackgroundSizeProps &
    X.BackgroundsProps &
    X.BorderBottomColorProps &
    X.BorderBottomProps &
    X.BorderBottomWidthProps &
    X.BorderCollapseProps &
    X.BorderColorProps &
    X.BorderLeftColorProps &
    X.BorderLeftProps &
    X.BorderLeftWidthProps &
    X.BorderProps &
    X.BorderRadiusProps &
    X.BorderRightColorProps &
    X.BorderRightProps &
    X.BorderRightWidthProps &
    X.BorderStyleProps &
    X.BorderTopColorProps &
    X.BorderTopProps &
    X.BorderTopWidthProps &
    X.BorderWidthProps &
    X.BordersProps &
    X.BottomProps &
    X.BoxShadowProps &
    X.BoxSizingProps &
    X.CSSFromProps &
    X.ColProps &
    X.ColorProps &
    X.ColumnGapProps &
    X.ContainerProps &
    X.CursorProps &
    X.DisplayProps &
    X.DivideColorProps &
    X.DivideStyleProps &
    X.DivideXProps &
    X.DivideXReverseProps &
    X.DivideYProps &
    X.DivideYReverseProps &
    X.EffectsProps &
    X.FillProps &
    X.FlexBasisProps &
    X.FlexDirectionProps &
    X.FlexGrowProps &
    X.FlexProps &
    X.FlexShrinkProps &
    X.FlexWrapProps &
    X.FlexboxGridsProps &
    X.FlexboxesProps &
    X.FloatProps &
    X.FontFamilyProps &
    X.FontSizeProps &
    X.FontStyleProps &
    X.FontWeightProps &
    X.GapProps &
    X.GradientFromProps &
    X.GradientToProps &
    X.GradientViaProps &
    X.GridAreaProps &
    X.GridAutoColumnsProps &
    X.GridAutoFlowProps &
    X.GridAutoRowsProps &
    X.GridColumnProps &
    X.GridRowProps &
    X.GridTemplateAreasProps &
    X.GridTemplateColumnsProps &
    X.GridTemplateRowsProps &
    X.GridsProps &
    X.HeightProps &
    X.InteractivityProps &
    X.JustifyContentProps &
    X.JustifyItemsProps &
    X.JustifySelfProps &
    X.LayoutProps &
    X.LeftProps &
    X.LetterSpacingProps &
    X.LineHeightProps &
    X.ListStylePositionProps &
    X.ListStyleTypeProps &
    X.MarginBottomProps &
    X.MarginLeftProps &
    X.MarginProps &
    X.MarginRightProps &
    X.MarginTopProps &
    X.MarginXProps &
    X.MarginYProps &
    X.MaskSizeProps &
    X.MaxHeightProps &
    X.MaxWidthProps &
    X.MinHeightProps &
    X.MinWidthProps &
    X.ObjectFitProps &
    X.OpacityProps &
    X.OrderProps &
    X.OutlineColorProps &
    X.OutlineProps &
    X.OutlineStyleProps &
    X.OutlineWidthProps &
    X.OverflowProps &
    X.OverflowXProps &
    X.OverflowYProps &
    X.OverscrollBehaviorProps &
    X.PaddingBottomProps &
    X.PaddingLeftProps &
    X.PaddingProps &
    X.PaddingRightProps &
    X.PaddingTopProps &
    X.PaddingXProps &
    X.PaddingYProps &
    X.PointerEventsProps &
    X.PositionProps &
    X.ResizeProps &
    X.RightProps &
    X.RingColorProps &
    X.RingInsetProps &
    X.RingProps &
    X.RotateProps &
    X.RowGapProps &
    X.RowProps &
    X.ScaleProps &
    X.ScaleXProps &
    X.ScaleYProps &
    X.SizingProps &
    X.SkewXProps &
    X.SkewYProps &
    X.SpaceProps &
    X.SpaceXProps &
    X.SpaceXReverseProps &
    X.SpaceYProps &
    X.SpaceYReverseProps &
    X.StrokeProps &
    X.SvgProps &
    X.SystemProps &
    X.TableLayoutProps &
    X.TablesProps &
    X.TextAlignProps &
    X.TextDecorationProps &
    X.TextOverflowProps &
    X.TextProps &
    X.TextShadowProps &
    X.TextTransformProps &
    X.TopProps &
    X.TransformOriginProps &
    X.TransformProps &
    X.TransformsProps &
    X.TransitionDelayProps &
    X.TransitionDurationProps &
    X.TransitionPropertyProps &
    X.TransitionProps &
    X.TransitionTimingFunctionProps &
    X.TransitionsProps &
    X.TranslateXProps &
    X.TranslateYProps &
    X.TypographyProps &
    X.UserSelectProps &
    X.VerticalAlignProps &
    X.VisibilityProps &
    X.WhiteSpaceProps &
    X.WidthProps &
    X.ZIndexProps
>;
